#!/usr/bin/env python3
"""Writes the SquawkIt app icon, the record stack, to every place a platform reads it from.

The stack is three plates in perspective: two instrument blues under a honey top, on a vellum
ground. `app-icon-record-stack.svg`, beside this script, is the master artwork, with soft shadows.

Android cannot use that file. An adaptive icon is a foreground over a background, each a vector
drawable, and vector drawables have no blur, so the plates are redrawn here from the same numbers
with hard contact shadows. The numbers are the ones in core/ui/.../brand/BrandStackGeometry.kt.

Everywhere else takes a PNG, rendered from the master by headless Chrome and resized by `sips`,
so this part runs on a Mac with Chrome installed.

    python3 docs/branding/render_app_icon.py
"""
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MASTER = Path(__file__).with_name("app-icon-record-stack.svg")
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
ANDROID_RES = REPO / "app/src/main/res/drawable"
IOS_ICON = REPO / "iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png"

# The master draws the stack at this scale about the centre of its 1024 box.
MASTER_SCALE = "scale(1.12)"

CENTRE_X, HALF_WIDTH, HALF_HEIGHT = 512, 250, 130
THICKNESS, CORNER_STROKE = 38, 44
FACE_Y = [626, 512, 398]  # bottom plate first

# Per plate: the face's gradient, start and end, then the flat edge colour.
PLATES = [
    ("#1F68BC", "#124F97", "#0A3870"),
    ("#66A8F2", "#3F8ADF", "#1F68BC"),
    ("#F4D48F", "#E4A94B", "#B27A24"),
]
GROUND = ("#FFFFFF", "#D9E1EC")  # top to bottom

# A plate's shadow on the face below it: how far down it falls, and how dark.
SHADOW_DROP, SHADOW = 18, "#33000000"

# An adaptive icon shows the middle 72dp of a 108dp layer and may mask that to a circle 66dp
# across, so the stack is drawn at this scale about the centre to sit inside the circle.
ADAPTIVE_SCALE = 0.75

# A themed icon is one flat colour, so the plates cannot overlap: the lower two are cut back to
# the part that shows, with this much clear space under the plate above.
MONO_GAP, MONO_STROKE = 56, 16


def diamond(y):
    return (f"M{CENTRE_X},{y - HALF_HEIGHT}L{CENTRE_X + HALF_WIDTH},{y}"
            f"L{CENTRE_X},{y + HALF_HEIGHT}L{CENTRE_X - HALF_WIDTH},{y}Z")


def silhouette(y):
    """A whole plate, face and edge, as one outline."""
    left, right = CENTRE_X - HALF_WIDTH, CENTRE_X + HALF_WIDTH
    return (f"M{CENTRE_X},{y - HALF_HEIGHT}L{right},{y}L{right},{y + THICKNESS}"
            f"L{CENTRE_X},{y + THICKNESS + HALF_HEIGHT}L{left},{y + THICKNESS}L{left},{y}Z")


def chevron(y, above):
    """The part of the plate at `y` that shows under the plate at `above`, MONO_GAP clear of it."""
    left, right = CENTRE_X - HALF_WIDTH, CENTRE_X + HALF_WIDTH
    slope = HALF_HEIGHT / HALF_WIDTH
    cut = above + THICKNESS + MONO_GAP  # the cut line's height at the plate's left and right
    inset = (y - cut) / (2 * slope)     # where the cut meets the plate's own upper edges
    shoulder = y - slope * inset
    return (f"M{left},{y}L{left + inset:.1f},{shoulder:.1f}L{CENTRE_X},{cut + HALF_HEIGHT}"
            f"L{right - inset:.1f},{shoulder:.1f}L{right},{y}L{right},{y + THICKNESS}"
            f"L{CENTRE_X},{y + THICKNESS + HALF_HEIGHT}L{left},{y + THICKNESS}Z")


def gradient(colors, x1, y1, x2, y2, attr):
    return (f'      <aapt:attr name="android:{attr}">\n'
            f'        <gradient android:type="linear" android:startX="{x1}" android:startY="{y1}"'
            f' android:endX="{x2}" android:endY="{y2}"\n'
            f'          android:startColor="{colors[0]}" android:endColor="{colors[1]}" />\n'
            f'      </aapt:attr>\n')


def flat(path, color, stroke=CORNER_STROKE, indent="    "):
    return (f'{indent}<path android:pathData="{path}"\n'
            f'{indent}  android:fillColor="{color}" android:strokeColor="{color}"\n'
            f'{indent}  android:strokeWidth="{stroke}" android:strokeLineJoin="round" />\n')


def vector(body, note):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- GENERATED by docs/branding/render_app_icon.py. {note} -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '  xmlns:aapt="http://schemas.android.com/aapt"\n'
            '  android:width="108dp"\n  android:height="108dp"\n'
            '  android:viewportWidth="1024"\n  android:viewportHeight="1024">\n'
            f'{body}</vector>\n')


def scaled(body):
    return (f'  <group android:pivotX="512" android:pivotY="512"\n'
            f'    android:scaleX="{ADAPTIVE_SCALE}" android:scaleY="{ADAPTIVE_SCALE}">\n'
            f'{body}  </group>\n')


def android_foreground():
    body = ""
    for plate, (start, end, edge) in enumerate(PLATES):
        y = FACE_Y[plate]
        box = (CENTRE_X - HALF_WIDTH, y - HALF_HEIGHT, CENTRE_X + HALF_WIDTH, y + HALF_HEIGHT)
        body += flat(diamond(y + THICKNESS), edge)
        body += (f'    <path android:pathData="{diamond(y)}"\n'
                 f'      android:strokeWidth="{CORNER_STROKE}" android:strokeLineJoin="round">\n'
                 + gradient((start, end), *box, "fillColor")
                 + gradient((start, end), *box, "strokeColor")
                 + '    </path>\n')
        if plate + 1 < len(PLATES):
            cast = diamond(FACE_Y[plate + 1] + THICKNESS + SHADOW_DROP)
            body += (f'    <group>\n      <clip-path android:pathData="{diamond(y)}" />\n'
                     + flat(cast, SHADOW, indent="      ") + '    </group>\n')
    return vector(scaled(body), "The record stack, for the adaptive icon's foreground.")


def android_background():
    body = ('  <path android:pathData="M0,0H1024V1024H0Z">\n'
            + gradient(GROUND, 0, 0, 0, 1024, "fillColor").replace("      ", "    ")
            + '  </path>\n')
    return vector(body, "The vellum ground, for the adaptive icon's background.")


def android_monochrome():
    top = FACE_Y[-1]
    body = flat(silhouette(top), "#FF000000")
    for plate in range(len(PLATES) - 2, -1, -1):
        body += flat(chevron(FACE_Y[plate], FACE_Y[plate + 1]), "#FF000000", MONO_STROKE)
    return vector(scaled(body), "The record stack in one flat colour, for themed icons.")


def render(out, size, rounded=False, scale=None):
    """Renders the master to a `size` pixel PNG at `out`.

    Square and opaque by default, with no alpha channel, which is what the stores and iOS require:
    they apply their own mask. `rounded` clips to a rounded tile on a transparent ground, for
    places that show the file as it is. `scale` redraws the stack larger or smaller on the ground.
    """
    svg = MASTER.read_text()
    assert MASTER_SCALE in svg, "the master no longer scales the stack the way this script expects"
    if scale is not None:
        svg = svg.replace(MASTER_SCALE, f"scale({scale})")
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        (tmp / "icon.svg").write_text(svg)
        radius = "22.4%" if rounded else "0"
        (tmp / "page.html").write_text(
            '<body style="margin:0"><img src="icon.svg" width="1024" height="1024"'
            f' style="display:block;border-radius:{radius}">')
        shot = tmp / "shot.png"
        command = [CHROME, "--headless=new", "--hide-scrollbars", "--force-device-scale-factor=1",
                   "--window-size=1024,1024", f"--screenshot={shot}"]
        if rounded:
            command.append("--default-background-color=00000000")
        subprocess.run(command + [(tmp / "page.html").as_uri()], check=True, capture_output=True)
        if size != 1024:
            subprocess.run(["sips", "-z", str(size), str(size), str(shot)],
                           check=True, capture_output=True)
        shutil.copyfile(shot, out)


def main():
    (ANDROID_RES / "ic_launcher_foreground.xml").write_text(android_foreground())
    (ANDROID_RES / "ic_launcher_background.xml").write_text(android_background())
    (ANDROID_RES / "ic_launcher_monochrome.xml").write_text(android_monochrome())
    render(IOS_ICON, 1024)


if __name__ == "__main__":
    main()
