pluginManagement {
  repositories {
    google {
      content {
        includeGroupByRegex("com\\.android.*")
        includeGroupByRegex("com\\.google.*")
        includeGroupByRegex("androidx.*")
      }
    }
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    gradlePluginPortal()
  }
}
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
  repositories {
    google()
    mavenCentral()
    maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
  }
}

rootProject.name = "wingslog"
include(":app")
include(":composeApp")
include(":core:model")
include(":core:datetime")
include(":core:nav")
include(":core:sharedassets")
include(":core:ui")
include(":core:ui:adaptive")
include(":core:ui:theme")
include(":core:ui:widget:avataricon")
include(":core:lifecycle")
include(":core:lifecycle:compose")
include(":core:appinfo")
include(":core:analytics")
include(":core:crash")
include(":core:auth")
include(":core:storage")
include(":core:template")
include(":core:firebase")
include(":core:di")
include(":feature:settings")
include(":feature:login")
include(":feature:userprofile:sharedassets")
include(":feature:logs:datamanager")
include(":feature:logs:sharedassets")
include(":feature:logs:viewing")
include(":feature:logs:update")
include(":feature:logs:di")
include(":feature:tasks:update")
include(":feature:tasks:model")
include(":feature:tasks:viewing")
include(":feature:tasks:sharedassets")

include(":feature:tasks:datamanager")
include(":feature:tasks:di")

include(":feature:sharing:model")
include(":feature:sharing:datamanager")
include(":feature:sharing:sharedassets")
include(":feature:sharing:viewing")
include(":feature:sharing:update")
include(":feature:sharing:di")
include(":feature:subscription:model")
include(":feature:subscription:datamanager")
include(":feature:subscription:viewing")
// Android + iOS only: wraps the RevenueCat SDK, which publishes no Kotlin/JS variant.
include(":feature:subscription:billing")
include(":feature:subscription:di")

include(":feature:fleet:datamanager")
include(":feature:fleet:picker:data")
include(":feature:fleet:sharedassets")
include(":feature:fleet:viewing")
include(":feature:fleet:di")
include(":feature:thing:dashboard")
include(":feature:thing:update")
include(":feature:thing:di")
include(":feature:sync:data")
include(":feature:sync:logging")
include(":feature:sync:settings")
include(":feature:sync:sharedassets")
include(":feature:sync:di")
include(":feature:technician:datamanager")
include(":feature:technician:manage")
include(":feature:technician:sharedassets")
include(":feature:technician:di")
include(":feature:attachment:model")
include(":feature:attachment:datamanager")
include(":feature:attachment:sharedassets")
include(":feature:attachment:viewing")
include(":feature:attachment:di")
include(":feature:export:datamanager")
include(":feature:export:sharedassets")
include(":feature:export:update")
include(":feature:export:di")
include(":feature:developeroptions:datamanager")
include(":feature:developeroptions:plugin")

include(":feature:comments:model")
include(":feature:comments:datamanager")
include(":feature:comments:sharedassets")
include(":feature:comments:viewing")

include(":feature:squawk:model")
include(":feature:squawk:datamanager")
include(":feature:squawk:sharedassets")
include(":feature:squawk:viewing")
include(":feature:squawk:update")
include(":feature:squawk:di")
include(":feature:search:model")
include(":feature:search:datamanager")
include(":feature:search:sharedassets")
include(":feature:search:viewing")

include(":feature:ads:model")
include(":feature:ads:datamanager")
include(":feature:ads:sharedassets")
include(":feature:ads:viewing")
include(":feature:ads:di")

include(":feature:notifications:model")
include(":feature:notifications:analytics")
include(":feature:notifications:permission")
include(":feature:notifications:viewing")
include(":feature:notifications:datamanager")
include(":feature:notifications:engine")
include(":feature:notifications:sharedassets")
include(":feature:notifications:settings")
include(":feature:notifications:devoptions")
include(":feature:notifications:di")

include(":feature:shell")

include(":feature:stresstest")
include(":feature:stresstest:config")
include(":webApp")
